---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: app
spec:
  generateSelector: true
  parentResource:
    apiVersion: devopstoolkitseries.com/v1
    resource: apps
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://app-controller.controllers/sync

---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: slack
spec:
  generateSelector: true
  parentResource:
    apiVersion: devopstoolkitseries.com/v1
    resource: apps
  hooks:
    sync:
      webhook:
        url: http://slack-controller.controllers:8080/slack
