---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.devopstoolkitseries.com
spec:
  group: devopstoolkitseries.com
  names:
    kind: App
    plural: apps
    singular: app
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
            required:
            - image
    subresources:
     status: {}

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: slacks.devopstoolkitseries.com
spec:
  group: devopstoolkitseries.com
  names:
    kind: Slack
    plural: slacks
    singular: slack
    shortNames:
    - sl
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
     status: {}